/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:ed5df1ca-6ad1-4097-89d4-b08a372bd804",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_jXhgbD1la",
    "aws_user_pools_web_client_id": "1ggom72ffieou13jpjfffva3r",
    "oauth": {
        "domain": "meeseeksbox25b0dfaa-25b0dfaa-dev.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://meeseeks.etm.tech,https://develop.d2auwz3pm5f9z7.amplifyapp.com,http://localhost:8080",
        "redirectSignOut": "",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://4uwuyj7ci5fwtgx4fkp23nstj4.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
